#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to use that shell, set the "SHELL" environment variable to
#       that shell, and run this script with that shell. If you don't have a
#       POSIX compliant shell, I urge you to port Gradle yourself, much of the
#       code in Gradle is written in Java and should be fairly easy to port
#       yourself. The worst thing that can happen is time spent waiting for
#       your choice of shell.
#
#   (2) The mutable state used by Gradle is contained in ~/.gradle and not in
#       this script. This means that things can go wrong if you run Gradle from
#       different scripts - for example from a GUI integrated development
#       environment you may run gradle tasks. When you later run gradle from the
#       command line, the daemon started by the GUI may be running on the old
#       JVM when a new one is installed.
#
#   (3) You may need to set other JVM options that are particular to your use
#       case (e.g. host and port of a proxy server). Some of these options can
#       be set using an GRADLE_OPTS environment variable, or by putting a
#       gradle.properties file in the source tree.
#
#   You may also want to set the following variables before running this
#   script, especially if you want to do it from automated processes:
#
#   GRADLE_HOME   - location of gradle installation.
#   GRADLE_OPTS   - parameters to pass to the Java VM when running Gradle.
#                   See the online documentation for more $@ options.
#   For start, stop and other commands, use the Gradle wrapper, e.g. "gradlew"
#
##############################################################################

if [ "$(uname)" = "Darwin" ] ; then
    APP_NAME="Gradle"
    APP_ARGS=$(printf '%s\n' "$@" | xargs -0)
else
    APP_NAME="Gradle"
    APP_ARGS=$(printf '%s\n' "$@")
fi

app_path=$()
while
    APP_HOME="${app_path%/}"
    [ -d "$APP_HOME" ]
do
  app_path="${APP_HOME%/*}"
  [ -z "$app_path" ] && app_path=/
  expr "$APP_HOME" : '.*/[^/]*$' > /dev/null 2>&1 || break
done
APP_HOME="$(cd "${APP_HOME:-.}" && pwd -P)" && export APP_HOME || exit

TRAP="exit 1"
if [ "${1:0:6}" = "--help" ] ; then
    "$APP_HOME/bin/gradle" --help "$@"
    exit
fi

if command -v java >/dev/null 2>&1 ; then
    IS_CYGWIN=$(case "$(uname)" in CYGWIN*) echo true ;; *) echo false ;; esac)
    IS_MSYS=$(case "$(uname)" in MSYS*) echo true ;; *) echo false ;; esac)
    IS_MINGW=$(case "$(uname)" in MINGW*) echo true ;; *) echo false ;; esac)
    IS_WSL=$([ -z "$WSLENV" ] && echo false || echo true)
    IS_WSL2=$(grep -qi microsoft /proc/version 2>/dev/null && echo true || echo false)

    if $IS_CYGWIN ; then
        APP_HOME=$(cygpath --path --mixed "$APP_HOME")
        CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
        JAVACMD=$(cygpath --windows "$JAVACMD")
        [ -n "$JAVA_HOME" ] &&
        JAVA_HOME=$(cygpath --path --mixed "$JAVA_HOME")
    fi

    if $IS_MSYS || $IS_MINGW ; then
        [ -n "$JAVA_HOME" ] &&
        JAVA_HOME=$(printf '%s\n' "$JAVA_HOME" | sed -e 's,\\,/,g')
    fi

    if $IS_WSL || $IS_WSL2 ; then
        CLASSPATH=$(printf '%s\n' "$CLASSPATH" |
            sed -e 's|C:\\|/mnt/c/|g' |
            sed -e 's|\\|/|g')
        [ -n "$JAVA_HOME" ] &&
        JAVA_HOME=$(printf '%s\n' "$JAVA_HOME" |
            sed -e 's|C:\\|/mnt/c/|g' |
            sed -e 's|\\|/|g')
    fi

    # Start the application
    exec "$JAVACMD" $GRADLE_OPTS -classpath "$APP_HOME/lib/*" org.gradle.wrapper.GradleWrapperMain "$@"
else
    echo 'ERROR: JAVA_HOME is not set and no \'java\' command could be found in your PATH.'
    echo ''
    echo 'Please set the JAVA_HOME variable in your environment to match the'
    echo 'location of your Java installation and try again.'
    exit 1
fi
